services:
  ntfy:
    build:
      context: ./ntfy
      args:
        TZ: "UTC+5:30"
    container_name: ntfy
    environment:
      TZ: "UTC+5:30"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - ngrok
    networks:
      - ntfy-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: 
      - "tunnel"
      - "--config"
      - "/etc/ngrok/ngrok.yml"
      - "ntfy"
    environment:
      - .env
    volumes:
      - ./ntfy/ngrok.yml:/etc/ngrok/ngrok.yml
    ports:
      - "4040:4040"  # ngrok web interface
    restart: unless-stopped
    networks:
      - ntfy-network

networks:
  ntfy-network:
    driver: bridge
